steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/shopdon-1614963409256/ecommerce-frontend:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/shopdon-1614963409256/ecommerce-frontend:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'donexp', '--region=us-central1', '--platform=managed', '--image=gcr.io/shopdon-1614963409256/ecommerce-frontend:$SHORT_SHA']
  
